version: '3'
services:
  app:
    build: './python'
    image: 'nfc_reader'
    container_name: 'nfc_reader'
    environment:
      TZ: Asia/Tokyo
    ports:
      - 80:5000
    volumes:
      - ./python/apps:/apps
    # to use USB device, privileged is required
    privileged: true
volumes:
  db:
